apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 10
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - data
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: es-data
        image: xanthoustech/es-k8s-search-guard:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: lionstep-elasticsearch
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms4g -Xmx4g
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 25m
            memory: 1536Mi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - plugins/search-guard-6/tools/sgadmin.sh
              - -h
              - "0.0.0.0"
              - -key
              - config/pipeline.key
              - -cert
              - config/pipeline.pem
              - -cacert
              - config/root-ca.pem
              - -nhnv
              - -icl
              - -si
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: config-volume
          mountPath: /elasticsearch/config
      volumes:
      - name: config-volume
        configMap:
          name: es-config
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: es-ssd
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 30Gi
